name: Discord Status Notification

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
            "content": "ビルドが完了しました！https://back-to-back.vercel.app/"
          }' \
          ${{ secrets.DISCORD_WEBHOOK_URL }}