name: Discord Status Notification

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
            "content": "リポジトリを更新しました！\nGitHubリポジトリ: https://github.com/kanbep2017/JavaAllProject"
          }' \
          ${{ secrets.DISCORD_WEBHOOK_URL }}